In [1]:
inp = '1'
out = '34'

In [3]:
import numpy as np

In [62]:
def check_arr(arr):
    ''' Checks if sum of all rows, columns and diagonals are same'''
    sum_diag_major = 0
    sum_diag_minor = 0
    for i in range(arr.shape[0]):
        sum_diag_major += arr[i][i]
        sum_diag_minor += arr[(arr.shape[0] - 1) - i][i]
    all_elems = np.concatenate((arr.sum(axis = 0),arr.sum(axis = 1), [sum_diag_major,sum_diag_minor]), axis = 0)
    all_equal = np.all(all_elems == all_elems[0])
    return all_equal

In [63]:
test_inp = np.random.randint(0, 3, size=(4,4))

In [64]:
print (test_inp, test_inp.shape)
print (test_inp.sum(axis = 0))

[[2 0 0 2]
 [2 0 2 1]
 [1 2 1 1]
 [0 2 1 2]] (4, 4)
[5 4 4 6]


In [65]:
print (check_arr(test_inp))

False


In [66]:
# Example in problem statement
test_inp_2 = np.array([[6, 3, 3, 0,],
[5, 0, 4, 3],
[0, 7, 1, 4],
[1, 2, 4, 5]])

In [67]:
print (check_arr(test_inp_2))

True


In [ ]:
def brute_force(arr, n):
    count_all_equal = 0
        